In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from nltk import PorterStemmer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("paramaggarwal/fashion-product-images-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/fashion-product-images-dataset

In [ ]:
styles = pd.read_csv('/kaggle/input/fashion-product-images-dataset/fashion-dataset/styles.csv', sep=',', on_bad_lines='skip')

In [ ]:
styles.shape
styles.isnull().sum()

id                      0
gender                  0
masterCategory          0
subCategory             0
articleType             0
baseColour             15
season                 21
year                    1
usage                 317
productDisplayName      7
dtype: int64

In [ ]:
styles.shape

(44424, 10)

In [ ]:
styles.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt
5,1855,Men,Apparel,Topwear,Tshirts,Grey,Summer,2011.0,Casual,Inkfruit Mens Chain Reaction T-shirt
6,30805,Men,Apparel,Topwear,Shirts,Green,Summer,2012.0,Ethnic,Fabindia Men Striped Green Shirt
7,26960,Women,Apparel,Topwear,Shirts,Purple,Summer,2012.0,Casual,Jealous 21 Women Purple Shirt
8,29114,Men,Accessories,Socks,Socks,Navy Blue,Summer,2012.0,Casual,Puma Men Pack of 3 Socks
9,30039,Men,Accessories,Watches,Watches,Black,Winter,2016.0,Casual,Skagen Men Black Watch

In [ ]:
images = pd.read_csv('/kaggle/input/fashion-product-images-dataset/fashion-dataset/images.csv', sep=',', on_bad_lines='skip')

In [ ]:
images.shape

(44446, 2)

In [ ]:
images.head()

    filename                                               link
0  15970.jpg  http://assets.myntassets.com/v1/images/style/p...
1  39386.jpg  http://assets.myntassets.com/v1/images/style/p...
2  59263.jpg  http://assets.myntassets.com/v1/images/style/p...
3  21379.jpg  http://assets.myntassets.com/v1/images/style/p...
4  53759.jpg  http://assets.myntassets.com/v1/images/style/p...

In [ ]:
images['id'] = images['filename'].apply(lambda x: int(x.split('.')[0]))
df = pd.merge(styles, images, on='id', how='inner')
display(df.head())

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,filename,link
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,15970.jpg,http://assets.myntassets.com/v1/images/style/p...
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,39386.jpg,http://assets.myntassets.com/v1/images/style/p...
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,59263.jpg,http://assets.myntassets.com/v1/images/style/p...
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,21379.jpg,http://assets.myntassets.com/v1/images/style/p...
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,53759.jpg,http://assets.myntassets.com/v1/images/style/p...

In [ ]:
df.shape

(44424, 12)

In [ ]:
df.isnull().sum()

id                      0
gender                  0
masterCategory          0
subCategory             0
articleType             0
baseColour             15
season                 21
year                    1
usage                 317
productDisplayName      7
filename                0
link                    0
dtype: int64

In [ ]:
# Fill missing values in specified columns with 'Unknown'
cols_to_fill = ['baseColour', 'season', 'usage', 'productDisplayName']
for col in cols_to_fill:
    df[col].fillna('Unknown', inplace=True)

# Verify that missing values have been handled
display(df.isnull().sum())

id                    0
gender                0
masterCategory        0
subCategory           0
articleType           0
baseColour            0
season                0
year                  1
usage                 0
productDisplayName    0
filename              0
link                  0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

id                    0
gender                0
masterCategory        0
subCategory           0
articleType           0
baseColour            0
season                0
year                  0
usage                 0
productDisplayName    0
filename              0
link                  0
dtype: int64

In [ ]:
df.head(10)

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,filename,link
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,15970.jpg,http://assets.myntassets.com/v1/images/style/p...
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,39386.jpg,http://assets.myntassets.com/v1/images/style/p...
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,59263.jpg,http://assets.myntassets.com/v1/images/style/p...
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,21379.jpg,http://assets.myntassets.com/v1/images/style/p...
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,53759.jpg,http://assets.myntassets.com/v1/images/style/p...
5,1855,Men,Apparel,Topwear,Tshirts,Grey,Summer,2011.0,Casual,Inkfruit Mens Chain Reaction T-shirt,1855.jpg,http://assets.myntassets.com/v1/images/style/p...
6,30805,Men,Apparel,Topwear,Shirts,Green,Summer,2012.0,Ethnic,Fabindia Men Striped Green Shirt,30805.jpg,http://assets.myntassets.com/v1/images/style/p...
7,26960,Women,Apparel,Topwear,Shirts,Purple,Summer,2012.0,Casual,Jealous 21 Women Purple Shirt,26960.jpg,http://assets.myntassets.com/v1/images/style/p...
8,29114,Men,Accessories,Socks,Socks,Navy Blue,Summer,2012.0,Casual,Puma Men Pack of 3 Socks,29114.jpg,http://assets.myntassets.com/v1/images/style/p...
9,30039,Men,Accessories,Watches,Watches,Black,Winter,2016.0,Casual,Skagen Men Black Watch,30039.jpg,http://assets.myntassets.com/v1/images/style/p...

In [ ]:
x = df['gender'] + df['masterCategory'] + df['subCategory'] + df['articleType'] + df['baseColour'] + df['season'] + df['usage'] + df['productDisplayName']
y = df['filename']

In [ ]:
print(x)

0        MenApparelTopwearShirtsNavy BlueFallCasualTurt...
1        MenApparelBottomwearJeansBlueSummerCasualPeter...
2        WomenAccessoriesWatchesWatchesSilverWinterCasu...
3        MenApparelBottomwearTrack PantsBlackFallCasual...
4        MenApparelTopwearTshirtsGreySummerCasualPuma M...
                               ...
44419    MenFootwearShoesCasual ShoesWhiteSummerCasualG...
44420    MenFootwearFlip FlopsFlip FlopsRedSummerCasual...
44421    MenApparelTopwearTshirtsBlueFallCasualPuma Men...
44422    WomenPersonal CareFragrancePerfume and Body Mi...
44423    WomenAccessoriesWatchesWatchesPinkWinterCasual...
Length: 44423, dtype: object

In [ ]:
print(y)

0        15970.jpg
1        39386.jpg
2        59263.jpg
3        21379.jpg
4        53759.jpg
           ...
44419    17036.jpg
44420     6461.jpg
44421    18842.jpg
44422    46694.jpg
44423    51623.jpg
Name: filename, Length: 44423, dtype: object

In [ ]:
stemmer = PorterStemmer()
x = x.apply(stemmer.stem)

In [ ]:
print(x)

0        menappareltopwearshirtsnavy bluefallcasualturt...
1        menapparelbottomwearjeansbluesummercasualpeter...
2        womenaccessorieswatcheswatchessilverwintercasu...
3        menapparelbottomweartrack pantsblackfallcasual...
4        menappareltopweartshirtsgreysummercasualpuma m...
                               ...
44419    menfootwearshoescasual shoeswhitesummercasualg...
44420    menfootwearflip flopsflip flopsredsummercasual...
44421    menappareltopweartshirtsbluefallcasualpuma men...
44422    womenpersonal carefragranceperfume and body mi...
44423    womenaccessorieswatcheswatchespinkwintercasual...
Length: 44423, dtype: object

In [ ]:
vector = TfidfVectorizer()
x = vector.fit_transform(x)

In [ ]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 272736 stored elements and shape (44423, 22596)>
  Coords	Values
  (0, 9577)	0.4482177697217716
  (0, 1975)	0.7270308698404542
  (0, 3547)	0.3190613398045276
  (0, 7391)	0.11832483738389676
  (0, 12100)	0.28678159607862624
  (0, 1901)	0.19953889783896606
  (0, 14155)	0.1807389938687674
  (1, 7391)	0.11395435105118247
  (1, 1901)	0.19216866141919678
  (1, 8486)	0.6086313631204462
  (1, 4543)	0.3913956289712286
  (1, 12678)	0.5503617117021382
  (1, 6581)	0.3515180268286598
  (2, 18708)	0.8125196361907414
  (2, 17270)	0.18850894515469216
  (2, 15176)	0.4256700429740064
  (2, 17070)	0.3508293501342754
  (3, 7391)	0.1040165005901215
  (3, 8666)	0.3807739286196697
  (3, 12541)	0.6635555701761581
  (3, 16761)	0.42038255919310513
  (3, 15316)	0.27109013988151065
  (3, 1858)	0.15251641085882275
  (3, 15986)	0.3611276402890572
  (4, 7391)	0.17241156333382537
  :	:
  (44419, 4968)	0.29153539152801994
  (44419, 15302)	0.49016180225345235
  (44419, 5229)	0.5260985086424651
  (44420, 7391)	0.10784244406265805
  (44420, 1901)	0.1818617536629862
  (44420, 16088)	0.2830440164916174
  (44420, 6053)	0.3903533553760724
  (44420, 10266)	0.5326697924800434
  (44420, 15479)	0.6626232297976111
  (44421, 1901)	0.1684895274898067
  (44421, 17270)	0.11994189552610134
  (44421, 1278)	0.22572053897983546
  (44421, 22450)	0.24320288631014372
  (44421, 3131)	0.30636554730022114
  (44421, 2315)	0.30196602376934895
  (44421, 12762)	0.3146436474010196
  (44421, 11612)	0.5502920165203627
  (44421, 6832)	0.5101593464962062
  (44422, 17270)	0.11493774658101574
  (44422, 17070)	0.21390780636868945
  (44422, 4182)	0.23521260096051927
  (44422, 3627)	0.3337092229980976
  (44422, 12834)	0.23495823459780796
  (44422, 18655)	0.588287966659758
  (44422, 4616)	0.610784616619325

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate cosine similarity between the vectorized text data
similarity_matrix = cosine_similarity(x)

def get_top_n_similar_items(item_index, similarity_matrix, n=10):
    """
    Gets the top N most similar items for a given item index.

    Args:
        item_index (int): The index of the item for which to find similar items.
        similarity_matrix (np.ndarray): The cosine similarity matrix.
        n (int): The number of top similar items to return.

    Returns:
        list: A list of indices of the top N most similar items (excluding the item itself).
    """
    # Get the similarity scores for the item at item_index
    similarity_scores = list(enumerate(similarity_matrix[item_index]))

    # Sort the items based on similarity scores in descending order
    sorted_similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Get the indices of the top N similar items (excluding the item itself)
    top_n_indices = [i[0] for i in sorted_similarity_scores[1:n+1]]

    return top_n_indices

# Example usage (finding top 10 similar items for the first item)
# You can change the index (0 in this case) to find similar items for other items.
# top_10_similar_items = get_top_n_similar_items(0, similarity_matrix, n=10)
# print("Top 10 similar items for the first item:", top_10_similar_items)

In [ ]:
from IPython.display import Image, display

# Example usage: Find top 10 similar items for the first item (index 0)
item_index = 1
top_10_indices = get_top_n_similar_items(item_index, similarity_matrix, n=10)

print(f"Top 10 similar items for item at index {item_index}:")

# Display product names, links and images for the similar items
for index in top_10_indices:
    product_name = df.iloc[index]['productDisplayName']
    product_link = df.iloc[index]['link']
    print(f"  - Index: {index}, Product: {product_name}, Link: {product_link}")
    try:
        display(Image(url=product_link, width=150, height=150))
    except Exception as e:
        print(f"Could not display image for index {index}: {e}")

Top 10 similar items for item at index 1:
  - Index: 3898, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/Peter-England-Men-Blue-Jeans_ffa64008b4811494f6e38a1dc13cc2db_images.jpg

  - Index: 10946, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/d1ae497127bb835ad6d4a57ede01171c_images.jpg

  - Index: 21243, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/Peter-England-Men-Blue-Jeans_f1df5d81d7a82784ba722b43d805a465_images.jpg

  - Index: 23710, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/efe156b5342db58626e6c67ee40e7318_images.jpg

  - Index: 27150, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/455aa6bc934adaaedccdfcb6a7abfea8_images.jpg

  - Index: 28030, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/73b505dcb9480fdc828cda1e535ce426_images.jpg

  - Index: 29850, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/Peter-England-Men-Blue-Jeans_c9339c668f21e00b5c0d02eb76f14cc7_images.jpg

  - Index: 30920, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/97cc44ded3bcc275ce99546963a9dd3c_images.jpg

  - Index: 35423, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/3f0ec388c1a62b386965c0ada0fd6917_images.jpg

  - Index: 40124, Product: Peter England Men Blue Jeans, Link: http://assets.myntassets.com/v1/images/style/properties/Peter-England-Men-Navy-Blue-Jeans_58fcc6284b638598c8fab5d7dc15c6ad_images.jpg